//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public string book_id { get; set; }
        public string book_name { get; set; }
        public string type_id { get; set; }
        public Nullable<short> amount { get; set; }
        public string author_name { get; set; }
    }
}
